Commit at 17:29 20.11.23

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,58 +1,58 @@
 name: Deploy to prod
 
 on:
-  push:
-    branches:
-      - main
+    push:
+        branches:
+            - main
 
 jobs:
-  deploy:
-    runs-on: ubuntu-22.04
+    deploy:
+        runs-on: ubuntu-22.04
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v4
 
-      - name: Stop Nginx
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.MAIN_SERVER_IP }}
-          username: ${{ secrets.DEPLOY_USER }}
-          password: ${{ secrets.MAIN_DEPLOY_PASSWORD }}
-          script: |
-            sudo systemctl stop nginx
+            - name: Stop Nginx
+              uses: appleboy/ssh-action@master
+              with:
+                  host: ${{ secrets.MAIN_SERVER_IP }}
+                  username: ${{ secrets.DEPLOY_USER }}
+                  password: ${{ secrets.MAIN_DEPLOY_PASSWORD }}
+                  script: |
+                      sudo systemctl stop nginx
 
-      - name: Deploy
-        uses: appleboy/scp-action@master
-        with:
-          host: ${{ secrets.MAIN_SERVER_IP }}
-          username: ${{ secrets.DEPLOY_USER }}
-          password: ${{ secrets.MAIN_DEPLOY_PASSWORD }}
-          source: "./build"
-          target: /home/deploy/Observer
+            - name: Deploy
+              uses: appleboy/scp-action@master
+              with:
+                  host: ${{ secrets.MAIN_SERVER_IP }}
+                  username: ${{ secrets.DEPLOY_USER }}
+                  password: ${{ secrets.MAIN_DEPLOY_PASSWORD }}
+                  source: "./build"
+                  target: /home/deploy/Observer
 
-      - name: Start Nginx
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.MAIN_SERVER_IP }}
-          username: ${{ secrets.DEPLOY_USER }}
-          password: ${{ secrets.MAIN_DEPLOY_PASSWORD }}
-          script: |
-            retries=0
+            - name: Start Nginx
+              uses: appleboy/ssh-action@master
+              with:
+                  host: ${{ secrets.MAIN_SERVER_IP }}
+                  username: ${{ secrets.DEPLOY_USER }}
+                  password: ${{ secrets.MAIN_DEPLOY_PASSWORD }}
+                  script: |
+                      retries=0
 
-            while [ $retries -lt 3 ]; do
-              sudo systemctl start nginx
-              if [ $? -eq 0 ]; then
-                echo "Successfully started Nginx."
-                break
-              else
-                echo "Failed to start Nginx. Retrying..."
-                retries=$((retries+1))
-                sleep 5
-              fi
-            done
+                      while [ $retries -lt 3 ]; do
+                        sudo systemctl start nginx
+                        if [ $? -eq 0 ]; then
+                          echo "Successfully started Nginx."
+                          break
+                        else
+                          echo "Failed to start Nginx. Retrying..."
+                          retries=$((retries+1))
+                          sleep 5
+                        fi
+                      done
 
-            if [ $retries -eq 3 ]; then
-              echo "Failed to start Nginx after 3 retries."
-              exit 1
-            fi
+                      if [ $retries -eq 3 ]; then
+                        echo "Failed to start Nginx after 3 retries."
+                        exit 1
+                      fi
